return { frengineer = {
  unitname            = [[frengineer]],
  name                = [[French Combat Engineer]],
  description         = [[Builds buildings reclaims resources]],

  energyUse              = 0,
  workerTime             = 25,
  buildTime              = 1,
  buildDistance          = 120,
  builder                = true,
  buildoptions           = {
    [[frbarracks]],
    [[frhangar]],
    [[frtankfactory]],
    [[frshipfactory]],
    [[trench]],
    [[starfort]],
    [[pillbox]],
  },

  acceleration        = 0.3,
  --autoHeal            = 0.1,
  brakeRate           = 2.7,
  buildCostMetal      = 10,
  buildPic            = [[vehcon.png]],
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  category            = [[LAND]],
  collisionVolumeOffsets = [[0 7 0]],
  collisionVolumeScales  = [[18 28 18]],
  collisionVolumeType    = [[CylY]],
  selectionVolumeOffsets = [[0 7 0]],
  selectionVolumeScales  = [[18 28 18]],
  selectionVolumeType    = [[CylY]],

  customParams        = {
    soundok_vol = [[0.58]],
    soundselect_vol = [[0.5]],
    bait_level_default = 0,
    aimposoffset      = [[0 0 0]],
    midposoffset      = [[0 10 0]],
    modelradius       = [[11]],
    selection_scale   = 0.35,

    outline_x = 0,
    outline_y = 0,
    outline_yoff = 0,
  },

  footprintX             = 2,
  footprintZ             = 2,
  iconType               = [[builder]],
  idleTime               = 150,
  leaveTracks            = true,
  maxDamage              = 230,
  maxSlope               = 36,
  maxVelocity            = 0.85,
  maxWaterDepth          = 22,
  movementClass          = [[KBOT2]],
  noAutoFire             = false,
  noChaseCategory        = [[TERRAFORM FIXEDWING SUB]],
  objectName          = [[frinfeng.dae]],
  script              = [[InfantryEng.lua]],

  showNanoSpray       = false,
  sightDistance          = 560,
  trackOffset            = 0,
  trackStrength          = 8,
  trackStretch           = 0.9,
  trackType              = [[ComTrack]],
  trackWidth             = 4,
  turnRate               = 2000,
  upright             = true,
  
} }

